version: '3.8'

services:
  # Flask Application Service (connects to local MSSQL)
  chatbot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - PYTHONPATH=/app
    env_file:
      - .env.production
    volumes:
      # Mount logs for debugging
      - ./logs:/app/logs
      # Mount uploads directory for persistence
      - ./uploads:/app/static/uploads
    networks:
      - chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: chatbot-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/var/www/static:ro
    depends_on:
      - chatbot
    networks:
      - chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  chatbot-network:
    driver: bridge
