version: '3.8'

services:
  # Flask Application Service (Development Mode)
  chatbot-app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: chatbot-flask-app-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - DEBUG=True
    env_file:
      - .env
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Mount logs for debugging
      - ./logs:/app/logs
      # Mount uploads directory for persistence
      - ./uploads:/app/static/uploads
    networks:
      - chatbot-network
    restart: unless-stopped
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
    depends_on:
      - redis

  # Redis Service for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: chatbot-redis-dev
    ports:
      - "6379:6379"
    networks:
      - chatbot-network
    restart: unless-stopped
    command: redis-server --appendonly yes

# Networks
networks:
  chatbot-network:
    driver: bridge
    name: chatbot-dev-network
