version: '3.8'

services:
  # Flask Application Service (using your local MSSQL database)
  chatbot-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    env_file:
      - .env
    volumes:
      # Mount logs for debugging
      - ./logs:/app/logs
      # Mount uploads directory for persistence
      - ./uploads:/app/static/uploads
    networks:
      - chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Network configuration
networks:
  chatbot-network:
    driver: bridge
