version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://chatbot_user:chatbot_pass@db:5432/chatbot_db
      - SECRET_KEY=production-secret-key-change-this
      - ADMIN_EMAIL=admin@youcloudpay.com
      - ADMIN_PASSWORD=secure-admin-password
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - chatbot_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=chatbot_db
      - POSTGRES_USER=chatbot_user
      - POSTGRES_PASSWORD=chatbot_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chatbot_network

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    networks:
      - chatbot_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - uploads_data:/app/uploads:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - chatbot_network

volumes:
  postgres_data:
  uploads_data:
  logs_data:


networks:
  chatbot_network:
    driver: bridge
