@echo off
echo Restarting Flask Application...
cd /d "c:\Users\prana\Downloads\chatbot_cloud"

echo Killing existing Python processes...
taskkill /f /im python.exe >nul 2>&1

echo Waiting for processes to stop...
timeout /t 3 /nobreak >nul

echo Starting Flask application...
python app.py
