version: '3.8'
services:
  mssql:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: chatbot-mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data:
