version: '3.8'

services:
  chatbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    environment:
      - FLASK_ENV=production
    volumes:
      - ../static/uploads:/app/static/uploads
      - ../translations:/app/translations
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/database/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
